### ISSUE TITLE
New 401 error cropping up sporadically on descriptive-metadata step

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/common-accessioning#117]
Over the last week or so, we've started seeing objects throw a 401 error at the descriptive-metadata step in common-accessioning. Upon investigation, it seems like these objects are failing to produce a descMetadata datastream at this step (or failed to have one created at registration).

It's a little difficult for me to tell what's supposed to happen here - but I would assume either something is going awry at registration, or descriptive-metadata step is not working as it used to.

As an example, https://argo.stanford.edu/view/druid:fy993bt2865 (though this is happening to non-ETD items, and to Collection objects as well).

A reset of the workflow step produced the following stack trace in the logs:

```
The client method is deprecated as of redis-rb 4.0.0, please use the new _clientmethod instead. Support for the old method will be removed in redis-namespace 2.0.
 INFO [2018-11-07 15:10:21] (2001)  :: druid:fy993bt2865 processing
ERROR [2018-11-07 15:10:22] (2001)  :: 401 Unauthorized
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
/usr/local/rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/net/http.rb:853:in `start'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:207:in `_follow_redirection'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:119:in `follow_redirection'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:95:in `return!'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
/usr/local/rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/net/http.rb:853:in `start'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.2/lib/restclient/resource.rb:51:in `get'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/dor-services-5.31.1/lib/dor/services/metadata_handlers/catalog_handler.rb:8:in `fetch'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/dor-services-5.31.1/lib/dor/services/metadata_service.rb:54:in `block in fetch'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/ruby-cache-0.3.0/lib/cache.rb:256:in `fetch'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/dor-services-5.31.1/lib/dor/services/metadata_service.rb:51:in `fetch'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/dor-services-5.31.1/lib/dor/models/concerns/describable.rb:32:in `fetch_descMetadata_datastream'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/dor-services-5.31.1/lib/dor/models/concerns/describable.rb:36:in `build_descMetadata_datastream'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/dor-services-5.31.1/lib/dor/models/concerns/processable.rb:88:in `build_datastream'
/home/lyberadmin/common-accessioning/releases/20180925160008/robots/accession/abstract_metadata.rb:21:in `perform'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/lyber-core-4.1.5/lib/lyber_core/robot.rb:66:in `block in work'
/usr/local/rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/lyber-core-4.1.5/lib/lyber_core/robot.rb:65:in `work'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/lyber-core-4.1.5/lib/lyber_core/robot.rb:18:in `perform'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/resque-1.27.4/lib/resque/job.rb:168:in `perform'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/resque-1.27.4/lib/resque/worker.rb:304:in `perform'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/resque-1.27.4/lib/resque/worker.rb:894:in `block in perform_with_fork'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/resque-1.27.4/lib/resque/worker.rb:892:in `fork'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/resque-1.27.4/lib/resque/worker.rb:892:in `perform_with_fork'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/resque-1.27.4/lib/resque/worker.rb:260:in `work_one_job'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/resque-1.27.4/lib/resque/worker.rb:234:in `block in work'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/resque-1.27.4/lib/resque/worker.rb:231:in `loop'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/resque-1.27.4/lib/resque/worker.rb:231:in `work'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/resque-1.27.4/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/bin/rake:22:in `load'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
```

**Comment by cbeer** [comment]
This is coming from the catalog service on dor-services-app. Is it possible the robots aren't sending the right credentials to the app (compare to argo, which seems to be making those requests successfully)?

**Comment by blalbrit** [comment]
Very possible - the errors are coming in from goobi, ETD, and gis content primarily, but occasionally on collection items. Robots credentials seems like a possibility.

**Comment by blalbrit** [comment]
Yep - interesting - it's anything *not* going through the registration page of Argo.

**Comment by blalbrit** [comment]
Thank you @cbeer - after updating the shared configs on all 5 robots machines, and restarting the accessioning robots on all 5 machines, the objects are now processing through as expected. I appreciate the quick spot on that, and the guidance through the fix.
