### ISSUE TITLE
 undefined method `dsid' for "descMetadata":String

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#165]
```
ERROR [2019-01-25 12:19:47] (30429)  :: undefined method `dsid' for "descMetadata":String
/opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/dor-services-6.1.10/lib/dor/services/datastream_builder.rb:51:in `datastream_name'
/opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/dor-services-6.1.10/lib/dor/services/datastream_builder.rb:85:in `find_metadata_file'
/opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/dor-services-6.1.10/lib/dor/services/datastream_builder.rb:46:in `filename'
/opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/dor-services-6.1.10/lib/dor/services/datastream_builder.rb:55:in `file_newer_than_datastream?'
/opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/dor-services-6.1.10/lib/dor/services/datastream_builder.rb:32:in `build'
/opt/app/lyberadmin/common-accessioning/releases/20190125195157/robots/accession/abstract_metadata.rb:27:in `perform'
/opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/lyber-core-4.1.5/lib/lyber_core/robot.rb:66:in `block in work'
/usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
``

**Comment by jcoyne** [comment]
Closed via #166
