### ISSUE TITLE
Can't run sdr-transfer robot on new staging machines

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#169]
```
 INFO [2019-01-25 14:54:31] (32111)  :: druid:kd050dp6039 processing
DEPRECATION WARNING: you are using dor-services to invoke calls to dor-services-app.  Use dor-services-client instead. (called from get_signature_catalog at /opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/dor-services-6.1.14/lib/dor/utils/sdr_client.rb:35)
** [Honeybadger] Reporting error id=f2ea9891-8256-4c95-bded-9d8f8a0c1e20 level=1 pid=32111
ERROR [2019-01-25 14:54:33] (32111)  :: undefined method `administrativeMetadata' for #<ActiveFedora::Base pid: "druid:yg077np2529">
/opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/activemodel-5.1.6.1/lib/active_model/attribute_methods.rb:432:in `method_missing'
/opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/dor-services-6.1.14/lib/dor/services/create_workflow_service.rb:42:in `default_workflow_lane'
/opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/dor-services-6.1.14/lib/dor/services/create_workflow_service.rb:21:in `create_workflow'
/opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/dor-services-6.1.14/lib/dor/services/create_workflow_service.rb:12:in `create_workflow'
/opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/dor-services-6.1.14/lib/dor/services/sdr_ingest_service.rb:40:in `transfer'
/opt/app/lyberadmin/common-accessioning/releases/20190125203628/robots/accession/sdr_ingest_transfer.rb:14:in `perform'
```

**Comment by jcoyne** [comment]
For some reason the APO `druid:yg077np2529` is loading as AF::Base rather than `AdminPolicyObject`

**Comment by jcoyne** [comment]
This looks like a data problem and @blalbrit has been alerted on Slack.

**Comment by blalbrit** [comment]
Fixed missing data model in APO, which is reporting weirdly in argo-stage. Going to re-run kd050pd6039 back through accessioning so that it gets to /dor/export.

**Comment by blalbrit** [comment]
At any rate: kd050pd6039 completed accessioning. Purl: https://sul-purl-test.stanford.edu/kd050dp6039 seems to have delivery issues, but I'm assuming that's more to do with environment.
