### ISSUE TITLE
Unable to create new robots that require models/etd

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/common-accessioning#296]
In the console, trying to create any `etd_submit` robot that `require`s `models/etd` fails with

```
LoadError: cannot load such file -- models/etd
from /opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
```

For example:

```
[lyberadmin@common-accessioning-prod-a current]$ ROBOT_ENVIRONMENT=production ./bin/console 
** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=4.2.2 framework=ruby level=1 pid=20913
Loading config from /opt/app/lyberadmin/common-accessioning/releases/20190514210757/config/environments/production
[1] pry(main)> Robots::DorRepo::EtdSubmit::CatalogStatus
LoadError: cannot load such file -- models/etd
from /opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
[2] pry(main)> Robots::DorRepo::EtdSubmit::CheckMarc
LoadError: cannot load such file -- models/etd
from /opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
[3] pry(main)> Robots::DorRepo::EtdSubmit::OtherMetadata
LoadError: cannot load such file -- models/etd
from /opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
[4] pry(main)> Robots::DorRepo::EtdSubmit::StartAccession
=> Robots::DorRepo::EtdSubmit::StartAccession
[5] pry(main)> Robots::DorRepo::EtdSubmit::SubmitMarc
LoadError: cannot load such file -- models/etd
from /opt/app/lyberadmin/common-accessioning/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
```

`StartAccession` does not require it, and returns a value.

**Comment by jcoyne** [comment]
Probably was broken by https://github.com/sul-dlss/common-accessioning/commit/431fad8f97cbb81f8b68cd53edaa30acb11d95b6
